### ISSUE TITLE
Build action fails to bundle js or css

### ISSUE THREAD

**Issue by u9g** [retypeapp/action-github#12]
Here's my repo: https://github.com/u9g/mineflayer-gitbook
Here's what the deployment looks like: https://u9g.github.io/mineflayer-gitbook/
It shows fine when using the watch command, however using the github pages, it doesn't bundle the js/css correctly so it doesn't look right.

**Comment by geoffreymcgill** [comment]
Please add a `retype.yml` file to the root of your project and set `url: u9g.github.io/mineflayer-gitbook/`. Here's a full sample:

```yml
input: .
output: .retype
url: u9g.github.io/mineflayer-gitbook/
branding:
  title: Project Name
  label: Docs
links:
  - text: Getting Started
    link: https://retype.com/guides/getting-started/
footer:
  copyright: "&copy; Copyright . All rights reserved."
```

Additional information on the `url` config available at https://retype.com/configuration/project/#url. 

Hope this helps.
